#!/usr/bin/env bash

#ddev-generated
## Description: Set up 1Password for use on macs as the SSH agent to be used globally for every client (not just DDEV!).
## Usage: 1password
## Example: "ddev 1password"
## ExecRaw: true

if [ "$(uname)" == "Darwin" ]; then
  # From https://developer.1password.com/docs/ssh/agent/compatibility/#configure-ssh_auth_sock-globally-for-every-client
  mkdir -p ~/Library/LaunchAgents
  cat << EOF > ~/Library/LaunchAgents/com.1password.SSH_AUTH_SOCK.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.1password.SSH_AUTH_SOCK</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>/bin/ln -sf $HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock \$SSH_AUTH_SOCK</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF
  launchctl load -w ~/Library/LaunchAgents/com.1password.SSH_AUTH_SOCK.plist
else
  echo "The \`ddev 1password\` command only works on mac hosts."
fi
