#ddev-generated
# Simple template to demonstrate 1password
services:
  1password:
    container_name: ddev-${DDEV_SITENAME}-1password
    image: ${1PASSWORD_DOCKER_IMAGE:-busybox:stable}
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
